### ISSUE TITLE
Add configurable damage to bows

### ISSUE THREAD

**Issue by shouxd** [Draylar/gate-of-babylon#27]
Bows right now feel like they all do the same damage. It'll be nice if you could multiply or add to the vanilla base damage

**Comment by Draylar** [comment]
Bows currently vary in durability and draw speed. I didn't include damage variation because I felt like standard bows were already viable end-game weapons, and buffing them _even more_ would make them incredibly busted. Maybe I'll add 1-2 extra damage on the end game bows and see how people feel about them.

**Comment by shouxd** [comment]
That explain things. I tested every bow damage and there were times where stone bow did more damage than a diamond one, which doesnt make sense. It'd be cool if there was an overall improvement because there are modpacks where mobs have a ton of health sometimes, but at least making this configurable should serve everyone good.

**Comment by Draylar** [comment]
In the next release, each bow will have a damage multiplier (Diamond: 1.25, Netherite: 1.5). This should help to make them feel like more viable weapon options.
