### ISSUE TITLE
Katana too overpowered

### ISSUE THREAD

**Issue by J3LL4** [Draylar/gate-of-babylon#30]
As far as I see it, I cannot find any disadvantage of using katana instead of a regular sword. Maybe some durability nerf? Or more damage nerf? Stone katana deals as much damage as an iron sword.

**Comment by Draylar** [comment]
In the next update, Katanas will have greatly nerfed base stats (with +1 damage and -1 speed over swords), but I have adjusted the Katana ability to deal 1.25x the weapon's power, as opposed to the .75x it was previously. This will keep Katanas leveled with Swords while also putting emphasis on using the ability rather than using it as a Sword replacement.
